// <auto-generated />
namespace GesNaturaMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pperc_sem_percurso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pperc_sem_percurso));
        
        string IMigrationMetadata.Id
        {
            get { return "201807131731300_pperc_sem_percurso"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
