// <auto-generated />
namespace GesNaturaMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class offNomePercurso_PercursoCriado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(offNomePercurso_PercursoCriado));
        
        string IMigrationMetadata.Id
        {
            get { return "201807191931492_offNomePercurso_PercursoCriado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
